server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/fitness_user_db"
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
